package assignment_two;

/* Generated By:JJTree: Do not edit this line. ASTaddExpr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTaddExpr extends SimpleNode {
  public ASTaddExpr(int id) {
    super(id);
  }

  public ASTaddExpr(BasicLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=97c9a0c3a05b5db3111bd02035ba57cb (do not edit this line) */
