package assignment_two;

/* Generated By:JJTree: Do not edit this line. ASTconst_decl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconst_decl extends SimpleNode {
  public ASTconst_decl(int id) {
    super(id);
  }

  public ASTconst_decl(BasicLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=55cca9b58f32d74be45f0242bacc6c9d (do not edit this line) */
