package assignment_two;

/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionCall extends SimpleNode {
  public ASTFunctionCall(int id) {
    super(id);
  }

  public ASTFunctionCall(BasicLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e743c8d3c8138e08bcbc5fb7077f9e04 (do not edit this line) */
