package assignment_two;

/* Generated By:JJTree: Do not edit this line. ASTmultExpr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmultExpr extends SimpleNode {
  public ASTmultExpr(int id) {
    super(id);
  }

  public ASTmultExpr(BasicLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=08593f6c3996abafe54745f7c94a014b (do not edit this line) */
