package assignment_two;

/* Generated By:JJTree: Do not edit this line. ASTminusExpr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTminusExpr extends SimpleNode {
  public ASTminusExpr(int id) {
    super(id);
  }

  public ASTminusExpr(BasicLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d7298264e2b64b3a6935a57903cd1f04 (do not edit this line) */
