package assignment_two;

/* Generated By:JJTree: Do not edit this line. ASTmain_prog.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmain_prog extends SimpleNode {
  public ASTmain_prog(int id) {
    super(id);
  }

  public ASTmain_prog(BasicLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=001e7b5da8d672a9eff3a98c4bf39a7d (do not edit this line) */
