package assignment_two;

/* Generated By:JJTree: Do not edit this line. ASTparam_list.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparam_list extends SimpleNode {
  public ASTparam_list(int id) {
    super(id);
  }

  public ASTparam_list(BasicLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BasicLParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c1c30449acc8d3a7420481c366df4a7e (do not edit this line) */
