package assignment_two;

/* Generated By:JavaCC: Do not edit this line. BasicLParserVisitor.java Version 6.0_1 */
public interface BasicLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTvar_decl node, Object data);
  public Object visit(ASTconst_decl node, Object data);
  public Object visit(ASTfunction node, Object data);
  public Object visit(ASTFunctionCall node, Object data);
  public Object visit(ASTparam_list node, Object data);
  public Object visit(ASTtype node, Object data);
  public Object visit(ASTmain_prog node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTassignment node, Object data);
  public Object visit(ASTaddExpr node, Object data);
  public Object visit(ASTminusExpr node, Object data);
  public Object visit(ASTmultExpr node, Object data);
  public Object visit(ASTdivExpr node, Object data);
  public Object visit(ASTbool node, Object data);
  public Object visit(ASTnumber node, Object data);
  public Object visit(ASTcondition node, Object data);
  public Object visit(ASTident_list node, Object data);
  public Object visit(ASTarg_list node, Object data);
  public Object visit(ASTidentifier node, Object data);
}
/* JavaCC - OriginalChecksum=c37be5b544202155f88163bf3c91720d (do not edit this line) */
