package assignment_two;

/* Generated By:JavaCC: Do not edit this line. BasicLParserTreeConstants.java Version 6.0_1 */
public interface BasicLParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR_DECL = 2;
  public int JJTCONST_DECL = 3;
  public int JJTFUNCTION = 4;
  public int JJTFUNCTIONCALL = 5;
  public int JJTPARAM_LIST = 6;
  public int JJTTYPE = 7;
  public int JJTMAIN_PROG = 8;
  public int JJTSTATEMENT = 9;
  public int JJTASSIGNMENT = 10;
  public int JJTADDEXPR = 11;
  public int JJTMINUSEXPR = 12;
  public int JJTMULTEXPR = 13;
  public int JJTDIVEXPR = 14;
  public int JJTBOOL = 15;
  public int JJTNUMBER = 16;
  public int JJTCONDITION = 17;
  public int JJTIDENT_LIST = 18;
  public int JJTARG_LIST = 19;
  public int JJTIDENTIFIER = 20;


  public String[] jjtNodeName = {
    "program",
    "void",
    "var_decl",
    "const_decl",
    "function",
    "FunctionCall",
    "param_list",
    "type",
    "main_prog",
    "statement",
    "assignment",
    "addExpr",
    "minusExpr",
    "multExpr",
    "divExpr",
    "bool",
    "number",
    "condition",
    "ident_list",
    "arg_list",
    "identifier",
  };
}
/* JavaCC - OriginalChecksum=2a44916b2a1d0807c3afc40ef8842536 (do not edit this line) */
