package assignment_two;

/* Generated By:JavaCC: Do not edit this line. BasicLParserDefaultVisitor.java Version 6.0_1 */
public class BasicLParserDefaultVisitor implements BasicLParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTprogram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvar_decl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTconst_decl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfunction node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionCall node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTparam_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTtype node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTmain_prog node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTassignment node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTaddExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTminusExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTmultExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTdivExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTbool node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnumber node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcondition node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTident_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTarg_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTidentifier node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=cdde4b5c067fbe9750d47a14facbace3 (do not edit this line) */
