package assignment_two;/* Generated By:JJTree&JavaCC: Do not edit this line. BasicLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasicLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int MINUS = 12;
  /** RegularExpression Id. */
  int MULTIPLY = 13;
  /** RegularExpression Id. */
  int DIVIDE = 14;
  /** RegularExpression Id. */
  int EQUALS = 15;
  /** RegularExpression Id. */
  int NOT_EQUALS = 16;
  /** RegularExpression Id. */
  int LESS_THAN = 17;
  /** RegularExpression Id. */
  int GREATER_THAN = 18;
  /** RegularExpression Id. */
  int LESS_THAN_OREQUAL = 19;
  /** RegularExpression Id. */
  int GREATER_THAN_OREQUAL = 20;
  /** RegularExpression Id. */
  int LPAREN = 21;
  /** RegularExpression Id. */
  int RPAREN = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int SEMICOLON = 24;
  /** RegularExpression Id. */
  int COLON = 25;
  /** RegularExpression Id. */
  int ASSIGN = 26;
  /** RegularExpression Id. */
  int LCBRACE = 27;
  /** RegularExpression Id. */
  int RCBRACE = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int BOOL = 30;
  /** RegularExpression Id. */
  int CONST = 31;
  /** RegularExpression Id. */
  int DO = 32;
  /** RegularExpression Id. */
  int ELSE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int IF = 35;
  /** RegularExpression Id. */
  int INT = 36;
  /** RegularExpression Id. */
  int MAIN = 37;
  /** RegularExpression Id. */
  int NOT = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int RETURN = 40;
  /** RegularExpression Id. */
  int THEN = 41;
  /** RegularExpression Id. */
  int TRUE = 42;
  /** RegularExpression Id. */
  int VAR = 43;
  /** RegularExpression Id. */
  int VOID = 44;
  /** RegularExpression Id. */
  int WHILE = 45;
  /** RegularExpression Id. */
  int BEGIN = 46;
  /** RegularExpression Id. */
  int END = 47;
  /** RegularExpression Id. */
  int NUMBER = 48;
  /** RegularExpression Id. */
  int IDENTIFIER = 49;
  /** RegularExpression Id. */
  int DIGIT = 50;
  /** RegularExpression Id. */
  int LETTER = 51;
  /** RegularExpression Id. */
  int UNDERSCORE = 52;
  /** RegularExpression Id. */
  int OTHER = 53;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTILINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\":=\"",
    "\"{\"",
    "\"}\"",
    "\"and\"",
    "\"bool\"",
    "\"const\"",
    "\"do\"",
    "\"else\"",
    "\"false\"",
    "\"if\"",
    "\"int\"",
    "\"main\"",
    "\"not\"",
    "\"or\"",
    "\"return\"",
    "\"then\"",
    "\"true\"",
    "\"var\"",
    "\"void\"",
    "\"while\"",
    "\"begin\"",
    "\"end\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<DIGIT>",
    "<LETTER>",
    "\"_\"",
    "<OTHER>",
  };

}
